<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mehdi Mlahfi">
<meta name="dcterms.date" content="2026-05-08">

<title>Live-Service vs Traditional Games: The Modern Gaming Dilemma – Live-Service vs Traditional Games</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-115391bca225cf340725c0ce7e2402d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Live-Service vs Traditional Games</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./blog.html" aria-current="page"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-live-service-games-matter" id="toc-why-live-service-games-matter" class="nav-link active" data-scroll-target="#why-live-service-games-matter">Why live-service games matter</a></li>
  <li><a href="#from-one-time-products-to-ongoing-platforms" id="toc-from-one-time-products-to-ongoing-platforms" class="nav-link" data-scroll-target="#from-one-time-products-to-ongoing-platforms">From one-time products to ongoing platforms</a></li>
  <li><a href="#data-and-classification" id="toc-data-and-classification" class="nav-link" data-scroll-target="#data-and-classification">Data and classification</a></li>
  <li><a href="#evidence-1-live-service-games-are-a-minority-of-the-sample" id="toc-evidence-1-live-service-games-are-a-minority-of-the-sample" class="nav-link" data-scroll-target="#evidence-1-live-service-games-are-a-minority-of-the-sample">Evidence 1: Live-service games are a minority of the sample</a></li>
  <li><a href="#evidence-2-player-activity-is-highly-concentrated" id="toc-evidence-2-player-activity-is-highly-concentrated" class="nav-link" data-scroll-target="#evidence-2-player-activity-is-highly-concentrated">Evidence 2: Player activity is highly concentrated</a></li>
  <li><a href="#evidence-3-retention-is-higher-but-less-clearly-so" id="toc-evidence-3-retention-is-higher-but-less-clearly-so" class="nav-link" data-scroll-target="#evidence-3-retention-is-higher-but-less-clearly-so">Evidence 3: Retention is higher, but less clearly so</a></li>
  <li><a href="#regression-analysis" id="toc-regression-analysis" class="nav-link" data-scroll-target="#regression-analysis">Regression analysis</a></li>
  <li><a href="#interpretation-scale-matters-more-than-retention" id="toc-interpretation-scale-matters-more-than-retention" class="nav-link" data-scroll-target="#interpretation-scale-matters-more-than-retention">Interpretation: Scale matters more than retention</a></li>
  <li><a href="#some-limitations-to-consider" id="toc-some-limitations-to-consider" class="nav-link" data-scroll-target="#some-limitations-to-consider">Some limitations to consider</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#appendix-regression-output" id="toc-appendix-regression-output" class="nav-link" data-scroll-target="#appendix-regression-output">Appendix: regression output</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Live-Service vs Traditional Games: The Modern Gaming Dilemma</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Evidence from top Steam games</p>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mehdi Mlahfi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="hero">
<p>Games are no longer just products that players buy once and complete. Many of the largest titles now operate as platforms: constantly updated, socially embedded, and designed to keep players returning. This post asks whether that model actually produces stronger player engagement.</p>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Research question
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Do live-service games achieve higher and more persistent player engagement than traditional games?</strong></p>
</div>
</div>
<section id="why-live-service-games-matter" class="level2">
<h2 class="anchored" data-anchor-id="why-live-service-games-matter">Why live-service games matter</h2>
<p>The video game industry has changed dramatically over the last two decades. What was once an industry built mainly around one-time purchases has increasingly shifted toward games designed as ongoing services. Today, many major titles use seasonal updates, online multiplayer ecosystems, battle passes, cosmetic stores, subscription services, and regular live events. In this model, games are not just products; they are platforms intended to keep players engaged continuously by manipulating them through FOMO (<em>Fear of missing out</em>).</p>
<p>Player attention has therefore become one of the gaming industry’s most valuable resources. A traditional game may sell millions of copies during launch week, but many players eventually move on once they finish the content. By contrast, live-service games are explicitly designed to encourage long-term engagement through progression systems, social interaction, limited-time events, and constant updates.</p>
<p>I am to compare live-service and traditional games using Steam player data. The analysis combines descriptive statistics with simple regression modelling to evaluate whether live-service games systematically differ from traditional games in terms of player engagement and retention.</p>
</section>
<section id="from-one-time-products-to-ongoing-platforms" class="level2">
<h2 class="anchored" data-anchor-id="from-one-time-products-to-ongoing-platforms">From one-time products to ongoing platforms</h2>
<p>Early video games in the 1980s and 1990s were constrained by hardware and distribution. Most titles were sold physically on cartridges or discs and were designed as complete experiences from release. Once players purchased a game, they owned the entire product. Multiplayer usually meant local play: friends sharing the same console or computer.</p>
<p>Widespread internet access changed this model. Developers could update games after release, host online servers, and maintain persistent worlds. This created the foundation for the live-service model. Games such as <em>RuneScape (2001)</em> and <em>World of Warcraft (2004)</em> showed that players were willing to pay continuously for games that continuously evolved.</p>
<p>That economic logic is central to the modern gaming industry. Traditional games rely heavily on launch sales. Live-service games generate ongoing revenue through subscriptions, cosmetic purchases, expansions, battle passes, and microtransactions. As a result, modern game design increasingly prioritises retention and engagement rather than only initial sales.</p>
</section>
<section id="data-and-classification" class="level2">
<h2 class="anchored" data-anchor-id="data-and-classification">Data and classification</h2>
<p>The dataset combines publicly available Steam player information with SteamCharts-style ranking data. The main variables are current active players, peak player counts, historical Steam activity, and game metadata. Each game was manually classified as either a live-service game or a traditional game.</p>
<p>A game is classified as <strong>live-service</strong> if it contains features such as ongoing seasonal updates, battle passes, persistent online progression, frequent live events, or a long-term multiplayer ecosystem. A game is classified as <strong>traditional</strong> if it is mainly structured around a one-time purchase or a relatively self-contained gameplay experience.</p>
<div id="22135fb1" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 21%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">live_service</th>
<th style="text-align: right;">games</th>
<th style="text-align: right;">mean_average_players</th>
<th style="text-align: right;">median_average_players</th>
<th style="text-align: right;">mean_peak_players</th>
<th style="text-align: right;">mean_retention</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Traditional</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">75715</td>
<td style="text-align: right;">62607</td>
<td style="text-align: right;">151149</td>
<td style="text-align: right;">0.507</td>
</tr>
<tr class="even">
<td style="text-align: left;">Live service</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">281740</td>
<td style="text-align: right;">127924</td>
<td style="text-align: right;">524219</td>
<td style="text-align: right;">0.541</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="evidence-1-live-service-games-are-a-minority-of-the-sample" class="level2">
<h2 class="anchored" data-anchor-id="evidence-1-live-service-games-are-a-minority-of-the-sample">Evidence 1: Live-service games are a minority of the sample</h2>
<p>Within the top 20 most-played Steam games in the sample, only 8 titles are classified as live-service games, while 12 are classified as traditional games.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/live_service_share.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Live-service and traditional games in the sample</figcaption>
</figure>
</div>
<p>This matters because the live-service model is often discussed as if it dominates the whole market. In this sample, live-service games are not the majority by count. Their importance comes from their concentration of player activity.</p>
</section>
<section id="evidence-2-player-activity-is-highly-concentrated" class="level2">
<h2 class="anchored" data-anchor-id="evidence-2-player-activity-is-highly-concentrated">Evidence 2: Player activity is highly concentrated</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/top_games_current_players.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Most-played Steam games in the sample</figcaption>
</figure>
</div>
<p>The distribution of player activity is extremely uneven. <em>Counter-Strike 2</em> dominates the sample, with <em>Dota 2</em> and <em>PUBG: Battlegrounds</em> also far ahead of most other games. This suggests a “winner-takes-most” structure: the live-service model can produce enormous success, but that success is concentrated among a small number of dominant titles.</p>
<p>The descriptive statistics support this pattern. Live-service games have a much higher mean current player count than traditional games. The mean for live-service games is about 281,740 players, compared with about 75,715 for traditional games. Median player counts also favour live-service games, though the gap is smaller, which shows that a few extremely successful games pull the live-service average upward.</p>
</section>
<section id="evidence-3-retention-is-higher-but-less-clearly-so" class="level2">
<h2 class="anchored" data-anchor-id="evidence-3-retention-is-higher-but-less-clearly-so">Evidence 3: Retention is higher, but less clearly so</h2>
<p>Player count alone does not fully capture engagement. A game may attract a large audience initially but fail to retain it. To estimate retention, I use the following ratio:</p>
<p><span class="math display">\[
\text{Retention} = \frac{\text{Current players}}{\text{Peak players}}
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/retention_boxplot.png" class="img-fluid figure-img" style="width:82.0%"></p>
<figcaption>Player retention by game model</figcaption>
</figure>
</div>
<p>The boxplot suggests that live-service games have somewhat higher retention. The mean retention ratio is 0.541 for live-service games and 0.507 for traditional games. One major reason is the use of recurring engagement systems such as: seasonal updates, collaboration events, cosmetic rewards, strong player feedback taken, social multiplayer ecosystems all built on strong community feedback.</p>
<p>A strong example is Fortnite’s “Astronomical” Travis Scott event in April 2020, which attracted over 27 million unique players across its limited-time concerts.</p>
<blockquote class="twitter-tweet blockquote">
<p lang="en" dir="ltr">
Thank you to everyone who attended and created content around the Travis Scott event! <br><br>Over 27.7 million unique players in-game participated live 45.8 million times across the five events to create a truly Astronomical experience. 🤯🔥 <a href="https://t.co/LSH0pLmGOS">pic.twitter.com/LSH0pLmGOS</a>
</p>
— Fortnite (<span class="citation" data-cites="Fortnite">@Fortnite</span>) <a href="https://twitter.com/Fortnite/status/1254817584676929537?ref_src=twsrc%5Etfw">April 27, 2020</a>
</blockquote>
<script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>However, the distributions overlap substantially. This means the descriptive difference is suggestive, but not decisive.</p>
</section>
<section id="regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="regression-analysis">Regression analysis</h2>
<p>To move beyond descriptive comparisons, I estimate two simple OLS regression models. The first examines whether live-service games are associated with larger active player bases:</p>
<p><span class="math display">\[
\log(\text{Current players}_i) = \alpha + \beta\text{LiveService}_i + \varepsilon_i
\]</span></p>
<p>The second examines whether live-service games are associated with higher retention:</p>
<p><span class="math display">\[
\text{Retention}_i = \alpha + \beta\text{LiveService}_i + \varepsilon_i
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Dependent variable</th>
<th style="text-align: right;">Live-service coefficient</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;">R-squared</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model 1</td>
<td style="text-align: right;">log current players</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.348</td>
<td>Live-service games have much larger active player bases.</td>
</tr>
<tr class="even">
<td>Model 2</td>
<td style="text-align: right;">retention</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">0.455</td>
<td style="text-align: right;">0.031</td>
<td>Live-service games have slightly higher retention, but the result is not statistically significant.</td>
</tr>
</tbody>
</table>
<p>Because Model 1 uses a logged dependent variable, the live-service coefficient can be interpreted approximately as a percentage difference. A coefficient of 1.000 implies that live-service games have about <strong>172%</strong> higher current player counts on average than traditional games. This is statistically significant at conventional levels.</p>
<p>Model 2 tells a different story. The live-service coefficient is positive, but small and statistically insignificant. This means the data does not provide strong evidence that live-service status alone explains better retention.</p>
</section>
<section id="interpretation-scale-matters-more-than-retention" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-scale-matters-more-than-retention">Interpretation: Scale matters more than retention</h2>
<p>The central finding is that live-service games appear much stronger on <strong>scale</strong> than on <strong>retention</strong>. They clearly attract and maintain larger active player communities. However, the evidence that they retain a higher proportion of their peak player base is weaker.</p>
<p>This distinction is important. It suggests that live-service success may rely less on a universally superior retention rate and more on network effects, social interaction, continuous content pipelines, and large existing communities. Once a live-service game becomes large, its size becomes part of its appeal: players join because other players are already there.</p>
<p>Traditional games operate differently. Their success is often based on delivering a complete, high-quality experience rather than maintaining constant engagement indefinitely. This does not make them inferior. It means they compete with a different strategy and player base in mind.</p>
</section>
<section id="some-limitations-to-consider" class="level2">
<h2 class="anchored" data-anchor-id="some-limitations-to-consider">Some limitations to consider</h2>
<p>There are several limitations to this analysis. First, the classification of live-service games was manually coded, so some borderline cases may be debatable. Second, the regressions should not be interpreted causally. Live-service status is not randomly assigned, and highly popular games may be more likely to adopt live-service mechanics because they already have large audiences. Third, Steam data does not capture the whole gaming market, especially console and mobile gaming. Finally, current players and peak players are imperfect measures of engagement because they cannot fully capture player satisfaction, loyalty, or monetisation.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The gaming industry has increasingly shifted toward live-service models because they create opportunities for continuous engagement and recurring revenue. This analysis finds strong evidence that live-service games maintain significantly larger active player bases than traditional games. However, the evidence that they retain players substantially better is weaker than expected.</p>
<p>The modern gaming dilemma is therefore not simply whether live-service games are more successful. It is whether the industry’s growing focus on continuous engagement changes what games are designed to be: complete experiences, or persistent platforms competing for player attention.</p>
</section>
<section id="appendix-regression-output" class="level2">
<h2 class="anchored" data-anchor-id="appendix-regression-output">Appendix: regression output</h2>
<div id="428324c0" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>MODEL 1: log_current_players on live_service
                             OLS Regression Results                            
===============================================================================
Dep. Variable:     log_current_players   R-squared:                       0.348
Model:                             OLS   Adj. R-squared:                  0.311
Method:                  Least Squares   F-statistic:                     9.594
Date:                 Thu, 07 May 2026   Prob (F-statistic):            0.00622
Time:                         18:07:14   Log-Likelihood:                -20.401
No. Observations:                   20   AIC:                             44.80
Df Residuals:                       18   BIC:                             46.79
Df Model:                            1                                         
Covariance Type:             nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           11.1214      0.204     54.463      0.000      10.692      11.550
live_service     1.0000      0.323      3.097      0.006       0.322       1.678
==============================================================================
Omnibus:                        1.773   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.412   Jarque-Bera (JB):                1.135
Skew:                           0.579   Prob(JB):                        0.567
Kurtosis:                       2.856   Cond. No.                         2.45
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

MODEL 2: retention on live_service
                            OLS Regression Results                            
==============================================================================
Dep. Variable:              retention   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                 -0.022
Method:                 Least Squares   F-statistic:                    0.5829
Date:                Thu, 07 May 2026   Prob (F-statistic):              0.455
Time:                        18:07:14   Log-Likelihood:                 19.262
No. Observations:                  20   AIC:                            -34.52
Df Residuals:                      18   BIC:                            -32.53
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5074      0.028     18.052      0.000       0.448       0.566
live_service     0.0339      0.044      0.763      0.455      -0.059       0.127
==============================================================================
Omnibus:                        0.088   Durbin-Watson:                   2.130
Prob(Omnibus):                  0.957   Jarque-Bera (JB):                0.267
Skew:                          -0.121   Prob(JB):                        0.875
Kurtosis:                       2.488   Cond. No.                         2.45
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Live-Service vs Traditional Games: The Modern Gaming Dilemma"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Evidence from top Steam games"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Mehdi Mlahfi"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-05-08"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: default</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">    smooth-scroll: true</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">    embed-resources: false</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: false</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="an">jupyter:</span><span class="co"> python3</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> pd.read_csv(<span class="st">"data/summary_by_model.csv"</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"mean_average_players"</span>] <span class="op">=</span> summary[<span class="st">"mean_average_players"</span>].<span class="bu">round</span>(<span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"median_average_players"</span>] <span class="op">=</span> summary[<span class="st">"median_average_players"</span>].<span class="bu">round</span>(<span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"mean_peak_players"</span>] <span class="op">=</span> summary[<span class="st">"mean_peak_players"</span>].<span class="bu">round</span>(<span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"mean_retention"</span>] <span class="op">=</span> summary[<span class="st">"mean_retention"</span>].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>live_effect_pct <span class="op">=</span> (math.exp(<span class="fl">1.0000</span>) <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>::: {.hero}</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>Games are no longer just products that players buy once and complete. Many of the largest titles now operate as platforms: constantly updated, socially embedded, and designed to keep players returning. This post asks whether that model actually produces stronger player engagement.</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>::: {.callout-note appearance="simple" icon=false}</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research question</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>**Do live-service games achieve higher and more persistent player engagement than traditional games?**</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why live-service games matter</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>The video game industry has changed dramatically over the last two decades. What was once an industry built mainly around one-time purchases has increasingly shifted toward games designed as ongoing services. Today, many major titles use seasonal updates, online multiplayer ecosystems, battle passes, cosmetic stores, subscription services, and regular live events. In this model, games are not just products; they are platforms intended to keep players engaged continuously by manipulating them through FOMO (*Fear of missing out*).</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>Player attention has therefore become one of the gaming industry's most valuable resources. A traditional game may sell millions of copies during launch week, but many players eventually move on once they finish the content. By contrast, live-service games are explicitly designed to encourage long-term engagement through progression systems, social interaction, limited-time events, and constant updates.</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>I am to compare live-service and traditional games using Steam player data. The analysis combines descriptive statistics with simple regression modelling to evaluate whether live-service games systematically differ from traditional games in terms of player engagement and retention.</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="fu">## From one-time products to ongoing platforms</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>Early video games in the 1980s and 1990s were constrained by hardware and distribution. Most titles were sold physically on cartridges or discs and were designed as complete experiences from release. Once players purchased a game, they owned the entire product. Multiplayer usually meant local play: friends sharing the same console or computer.</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>Widespread internet access changed this model. Developers could update games after release, host online servers, and maintain persistent worlds. This created the foundation for the live-service model. Games such as *RuneScape (2001)* and *World of Warcraft (2004)* showed that players were willing to pay continuously for games that continuously evolved.</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>That economic logic is central to the modern gaming industry. Traditional games rely heavily on launch sales. Live-service games generate ongoing revenue through subscriptions, cosmetic purchases, expansions, battle passes, and microtransactions. As a result, modern game design increasingly prioritises retention and engagement rather than only initial sales.</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data and classification</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>The dataset combines publicly available Steam player information with SteamCharts-style ranking data. The main variables are current active players, peak player counts, historical Steam activity, and game metadata. Each game was manually classified as either a live-service game or a traditional game.</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>A game is classified as **live-service** if it contains features such as ongoing seasonal updates, battle passes, persistent online progression, frequent live events, or a long-term multiplayer ecosystem. A game is classified as **traditional** if it is mainly structured around a one-time purchase or a relatively self-contained gameplay experience.</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>display(Markdown(summary.to_markdown(index<span class="op">=</span><span class="va">False</span>)))</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evidence 1: Live-service games are a minority of the sample</span></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>Within the top 20 most-played Steam games in the sample, only 8 titles are classified as live-service games, while 12 are classified as traditional games.</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a><span class="al">![Live-service and traditional games in the sample](figures/live_service_share.png)</span>{fig-align="center" width="80%"}</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>This matters because the live-service model is often discussed as if it dominates the whole market. In this sample, live-service games are not the majority by count. Their importance comes from their concentration of player activity.</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evidence 2: Player activity is highly concentrated</span></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a><span class="al">![Most-played Steam games in the sample](figures/top_games_current_players.png)</span>{fig-align="center" width="95%"}</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>The distribution of player activity is extremely uneven. *Counter-Strike 2* dominates the sample, with *Dota 2* and *PUBG: Battlegrounds* also far ahead of most other games. This suggests a “winner-takes-most” structure: the live-service model can produce enormous success, but that success is concentrated among a small number of dominant titles.</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>The descriptive statistics support this pattern. Live-service games have a much higher mean current player count than traditional games. The mean for live-service games is about 281,740 players, compared with about 75,715 for traditional games. Median player counts also favour live-service games, though the gap is smaller, which shows that a few extremely successful games pull the live-service average upward.</span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evidence 3: Retention is higher, but less clearly so</span></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a>Player count alone does not fully capture engagement. A game may attract a large audience initially but fail to retain it. To estimate retention, I use the following ratio:</span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>\text{Retention} = \frac{\text{Current players}}{\text{Peak players}}</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a><span class="al">![Player retention by game model](figures/retention_boxplot.png)</span>{fig-align="center" width="82%"}</span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>The boxplot suggests that live-service games have somewhat higher retention. The mean retention ratio is 0.541 for live-service games and 0.507 for traditional games. One major reason is the use of recurring engagement systems such as: seasonal updates, collaboration events, cosmetic rewards, strong player feedback taken, social multiplayer ecosystems all built on strong community feedback. </span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a>A strong example is Fortnite’s “Astronomical” Travis Scott event in April 2020, which attracted over 27 million unique players across its limited-time concerts. </span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">blockquote</span><span class="ot"> class</span><span class="op">=</span><span class="st">"twitter-tweet"</span><span class="dt">&gt;&lt;</span><span class="kw">p</span><span class="ot"> lang</span><span class="op">=</span><span class="st">"en"</span><span class="ot"> dir</span><span class="op">=</span><span class="st">"ltr"</span><span class="dt">&gt;</span>Thank you to everyone who attended and created content around the Travis Scott event! <span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>Over 27.7 million unique players in-game participated live 45.8 million times across the five events to create a truly Astronomical experience. 🤯🔥 <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"https://t.co/LSH0pLmGOS"</span><span class="dt">&gt;</span>pic.twitter.com/LSH0pLmGOS<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;&lt;/</span><span class="kw">p</span><span class="dt">&gt;</span><span class="dv">&amp;mdash;</span> Fortnite (@Fortnite) <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"https://twitter.com/Fortnite/status/1254817584676929537?ref_src=twsrc%5Etfw"</span><span class="dt">&gt;</span>April 27, 2020<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;&lt;/</span><span class="kw">blockquote</span><span class="dt">&gt;</span> <span class="dt">&lt;</span><span class="kw">script</span><span class="ot"> async src</span><span class="op">=</span><span class="st">"https://platform.twitter.com/widgets.js"</span><span class="ot"> charset</span><span class="op">=</span><span class="st">"utf-8"</span><span class="dt">&gt;&lt;/</span><span class="kw">script</span><span class="dt">&gt;</span></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a>However, the distributions overlap substantially. This means the descriptive difference is suggestive, but not decisive.</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a><span class="fu">## Regression analysis</span></span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a>To move beyond descriptive comparisons, I estimate two simple OLS regression models. The first examines whether live-service games are associated with larger active player bases:</span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a>\log(\text{Current players}_i) = \alpha + \beta\text{LiveService}_i + \varepsilon_i</span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a>The second examines whether live-service games are associated with higher retention:</span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a>\text{Retention}_i = \alpha + \beta\text{LiveService}_i + \varepsilon_i</span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model <span class="pp">|</span> Dependent variable <span class="pp">|</span> Live-service coefficient <span class="pp">|</span> p-value <span class="pp">|</span> R-squared <span class="pp">|</span> Interpretation <span class="pp">|</span></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|---|</span></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model 1 <span class="pp">|</span> log current players <span class="pp">|</span> 1.000 <span class="pp">|</span> 0.006 <span class="pp">|</span> 0.348 <span class="pp">|</span> Live-service games have much larger active player bases. <span class="pp">|</span></span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model 2 <span class="pp">|</span> retention <span class="pp">|</span> 0.034 <span class="pp">|</span> 0.455 <span class="pp">|</span> 0.031 <span class="pp">|</span> Live-service games have slightly higher retention, but the result is not statistically significant. <span class="pp">|</span></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a>Because Model 1 uses a logged dependent variable, the live-service coefficient can be interpreted approximately as a percentage difference. A coefficient of 1.000 implies that live-service games have about **172%** higher current player counts on average than traditional games. This is statistically significant at conventional levels.</span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a>Model 2 tells a different story. The live-service coefficient is positive, but small and statistically insignificant. This means the data does not provide strong evidence that live-service status alone explains better retention.</span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation: Scale matters more than retention</span></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a>The central finding is that live-service games appear much stronger on **scale** than on **retention**. They clearly attract and maintain larger active player communities. However, the evidence that they retain a higher proportion of their peak player base is weaker.</span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a>This distinction is important. It suggests that live-service success may rely less on a universally superior retention rate and more on network effects, social interaction, continuous content pipelines, and large existing communities. Once a live-service game becomes large, its size becomes part of its appeal: players join because other players are already there.</span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a>Traditional games operate differently. Their success is often based on delivering a complete, high-quality experience rather than maintaining constant engagement indefinitely. This does not make them inferior. It means they compete with a different strategy and player base in mind.</span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a><span class="fu">## Some limitations to consider</span></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a>There are several limitations to this analysis. First, the classification of live-service games was manually coded, so some borderline cases may be debatable. Second, the regressions should not be interpreted causally. Live-service status is not randomly assigned, and highly popular games may be more likely to adopt live-service mechanics because they already have large audiences. Third, Steam data does not capture the whole gaming market, especially console and mobile gaming. Finally, current players and peak players are imperfect measures of engagement because they cannot fully capture player satisfaction, loyalty, or monetisation.</span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a>The gaming industry has increasingly shifted toward live-service models because they create opportunities for continuous engagement and recurring revenue. This analysis finds strong evidence that live-service games maintain significantly larger active player bases than traditional games. However, the evidence that they retain players substantially better is weaker than expected.</span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a>The modern gaming dilemma is therefore not simply whether live-service games are more successful. It is whether the industry's growing focus on continuous engagement changes what games are designed to be: complete experiences, or persistent platforms competing for player attention.</span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="fu">## Appendix: regression output</span></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(Path(<span class="st">"appendix/regression_results.txt"</span>).read_text())</span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>